name: CI

on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk+fx

    - name: Free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h

    - name: Cache maven repo
      uses: actions/cache@v2
      if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
      with:
        path: ~/.m2/repository/p2/osgi/bundle/com.?1c.*
        key: ${{ runner.os }}-maven-latest-${{ hashFiles('**/pom.xml') }}-${{ hashFiles('targets/default/default.target') }}
        restore-keys: |
          ${{ runner.os }}-maven-latest-
  
    - name: Build with Maven
      working-directory: ./
      run: |
        Xvfb :5 -screen 0 1280x1024x8 -fbdir /tmp &
        export DISPLAY=:5
        mvn clean verify -Pfind-bugs -Dtycho.localArtifacts=ignore -B -V  -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      if: github.event.pull_request.head.repo.full_name == github.repository
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload repo
      uses: actions/upload-artifact@v2
      with:
        name: dt-unit-repository
        path: repositories/ru.capralow.dt.unit.repository/target/repository/
        
    - name: Upload JaCoCo exec data
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: jacoco
        path: |
          ./**/target/jacoco.exec
          ./**/target/site/jacoco*/
    
    - name: Upload test logs on failure
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: logs
        path: ./**/.log

    - name: Upload repo to ftp on success
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      if: success()
      with:
        server: capralow.ru
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: 1unit/0.4.1/
        local-dir: repositories/ru.capralow.dt.unit.repository/target/repository/
